# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Choose a theme.
#   Latest themes (may require updating Academic): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme = "minimal"

# Enable users to switch between day and night mode?
day_night = true

# Overrride the theme's font set (optional).
#   Latest font sets (may require updating Academic): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font = ""

# Choose a font size.
# Sizes: s (small), m (medium), l (large)
font_size = "m"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = ""

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
math = false

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Enable visitors to edit pages?
# `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page = {repo_url = "", repo_branch = "master", editable = {docs = true, page = false, post = false}}

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

############################
## Contact Widget setup   ##
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "asif.neloy@northsouth.edu"
phone = "+8801860826446"
#address = "Building 1 Room 1, Stanford University, California, 90210, USA"

# Office hours: use `<br>` to insert a line break, or set to "" to remove office hours
office_hours = """Sunday 11:00 to 13:00<br>
                  Tuesday 11:00 to 14:00<br>
                  Saturday 11.00 to 15.00 (make an appointment earlier)<br>
                  """

# Enter an optional link for booking appointments (e.g. calendly.com).
#appointment_url = "https://calendly.com"

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "far fa-comments", icon_pack = "fa", name = "Email", link = "mailto:asif.neloy@northsouth.edu"},
  #{icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
  #{icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  #{icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  #{icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]



############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_css = []
plugins_js  = []

############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Align the main menu to the right of the page? (true/false)
menu_align_right = false

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Publication list format.
  #   0 = Simple
  #   1 = Detailed
  #   2 = APA
  #   3 = MLA
  #   4 = Stream
  post_view = 2
  publication_view = 1
  talk_view = 2

[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true}

  # Configuration of Disqus.
[comments.disqus]
  shortname = ""  # Paste the shortname from your Disqus dashboard.
  show_count = true  # Show comment count in page header? (true/false)
  